### ISSUE TITLE
Undefined Function

### ISSUE THREAD

**Issue by diskret** [ianbarber/Yourls-APC-Cache#2]
Hi Ian,
When I try to use APC for Yourls,
I got some erros:

"Fatal error: Call to undefined function yourls_add_action() in /home/***/public_html/user/plugins/apc-cache/plugin.php on line 29"

**Comment by ianbarber** [comment]
That's a bit odd, that's one of the standard plugin controllers.  Which version of Yourls are you using? Did this happen when you clicked the 'activate' link in the yourls plugin admin page?

**Comment by diskret** [comment]
My Yourls is v1.5 
Not when click activate.
I activated, set cache.php (path url)
when I call cache.php from /user folder.. 
gave me this error:

"Fatal error: Call to undefined function yourls_add_action() in /home/****/public_html/user/plugins/apc-cache/plugin.php on line 29"

**Comment by ianbarber** [comment]
You shouldn't need to call cache.php - that is automatically included by Yourls if it is present
