### ISSUE TITLE
Pull request or diverging projects?

### ISSUE THREAD

**Issue by tipichris** [ianbarber/Yourls-APC-Cache#8]
Hi @ianbarber 

Not really an issue, but I couldn't figure out another way to contact you. I [forked Yourls-APC-Cache](https://github.com/tipichris/Yourls-APC-Cache) to have a play with, intending that if I came up with anything useful I'd make a pull request. But I got carried away and made some fairly big changes. I'm now wondering if the approach of just releasing what I have as an alternative works better, giving people the choice of which YOURLS plugin to use. What would you suggest?

Bigger changes include:
- Different strategy for caching clicks. Instead of one timer for each URL I use a single timer for all URLs. This is somewhat more aggressive, ie clicks are more likely to be cached. It also means that multiple URLs are updated at the same time. By wrapping these in a transaction the transaction overhead is reduced (ie one transaction for multiple updates, rather than the one transaction per update implied by autocommit)
- Different approach to timers. I'm writing the time into an APC key and then checking that, rather than relying on the key's TTL. This gives me a bit more flexibility in the logic of when to write out
- Option to do writes on the basis of number of records cached as well as / instead of time since last write
- Delay writes if the server load exceeds a threshold
- An API call that can be used to trigger write out to the database. The idea being that this could be fired from cron so that writes are never going on in the same request as a redirect

Smaller changes include
- addressed issue #7 that I raised the other day
- avoid using YOURLS keywords as APC keys directly, in case they clash with some other process's keywords
- replace some do... while loops with while so that there is no sleep if not needed. This became particularly noticeable when I stress tested things doing 2000 url updates at once. Each reset of the key waited 500µs, adding 1s to the request time.

Let me know how you'd prefer to go.

**Comment by ianbarber** [comment]
Your call to be honest - the changes all sound great, and I haven't looked at this plugin for ages. I'm totally happy with you just going with a fork (and let me know the link and I'll add a reference in the README here). Alternatively, I can you add you a collaborator to this repo if you wanted to merge the changes in?

**Comment by tipichris** [comment]
I remain undecided! What concerns me about a pull request is that there are some big changes that have had limited testing, whilst the existing code has presumably been working in production environments for some time. I think if we do merge then the current state of master should at least be tagged so that it remains relatively easy to grab a copy of the code as it is today.

**Comment by tipichris** [comment]
Hi
I've decided to go with a fork of the project, using the name YAPCache. I've put this at https://github.com/tipichris/YAPCache
Thanks

**Comment by ianbarber** [comment]
Added a note in the README here, sorry for the slow turnaround!
